data_root: polyvore-u/processed/original/tuples_32
phase: train
dataset:
  data_mode: PairwiseOutfit
  pos_mode: "Fix"
  neg_mode: "RandomMix"
  neg_param: { ratio: 1, type_aware: true }
readers: [{ reader: TensorLMDB, path: polyvore-u/processed/features/resnet34 }]
batch_size: 4
num_workers: 1
shuffle: true
