data_root: maryland-polyvore/processed/original
phase: train
dataset:
  data_mode: PairwiseOutfit
  pos_mode: "Fix"
  neg_mode: "RandomMix"
  neg_param: { ratio: 1, type_aware: true }
readers:
  [{ reader: TensorLMDB, path: maryland-polyvore/processed/features/resnet34 }]
batch_size: 4
num_workers: 1
shuffle: true
